version: 0.1
phases:
  install:
    install:
      commands:
        - npm install --silent
        - aws cloudformation package --template-file template.yaml --s3-bucket $mybucketaxe --output-template-file output-template.yaml
artifacts:
  type: zip
  files:
  - '**/*'